In [3]:
import pandas as pd
import os

# Load the "in progress" pickle file
in_progress_pickle = 'in_progress.pkl'

# Check if the pickle file exists
if os.path.exists(in_progress_pickle):
    # Load the list of dictionaries
    with open(in_progress_pickle, 'rb') as f:
        in_progress_list = pd.read_pickle(f)
    
    # Convert the list of dictionaries to a DataFrame
    in_progress_df = pd.DataFrame(in_progress_list)
    
    # Display the first few rows to check the progress
    print(in_progress_df.head())
else:
    print("In-progress pickle file not found.")

                        _id         id  ratingsSummary_aggregateRating  \
0  61e58022d735dff3f9412891  tt0013274                             6.6
1  61e580eda66e596423414ce1  tt0070596                             7.5
2  61e58108b597b91eb941520b  tt0077684                             NaN
3  61e58148e1a8ddbd96415d31  tt0096235                             5.6
4  61e5814b78c012aa34415d3d  tt0097767                             7.0

   ratingsSummary_voteCount ratingsSummary___typename episodes  \
0                        71            RatingsSummary     None
1                        59            RatingsSummary     None
2                         0            RatingsSummary     None
3                        73            RatingsSummary     None
4                         6            RatingsSummary     None

  primaryImage_id  primaryImage_width  primaryImage_height  \
0    rm3867208705              2868.0               2154.0
1    rm2513434113              1233.0                871.0
2             NaN                 NaN                  NaN
3     rm493571328               350.0                472.0
4             NaN                 NaN                  NaN

                                    primaryImage_url  ...  \
0  https://m.media-amazon.com/images/M/MV5BMjBhZj...  ...
1  https://m.media-amazon.com/images/M/MV5BYTQ4Mz...  ...
2                                                NaN  ...
3  https://m.media-amazon.com/images/M/MV5BMzI2OD...  ...
4                                                NaN  ...

  prestigiousAwardSummary_wins prestigiousAwardSummary_award_text  \
0                          NaN                                NaN
1                          NaN                                NaN
2                          NaN                                NaN
3                          NaN                                NaN
4                          NaN                                NaN

  prestigiousAwardSummary_award_id prestigiousAwardSummary_award_event_id  \
0                              NaN                                    NaN
1                              NaN                                    NaN
2                              NaN                                    NaN
3                              NaN                                    NaN
4                              NaN                                    NaN

  prestigiousAwardSummary_award_event___typename  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN

   prestigiousAwardSummary_award___typename  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

   prestigiousAwardSummary___typename genres_genres_8_text genres_genres_8_id  \
0                                 NaN                  NaN                NaN
1                                 NaN                  NaN                NaN
2                                 NaN                  NaN                NaN
3                                 NaN                  NaN                NaN
4                                 NaN                  NaN                NaN

  genres_genres_8___typename
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN

[5 rows x 124 columns]

In [5]:
in_progress_df.describe()

,ratingsSummary_aggregateRating,ratingsSummary_voteCount,primaryImage_width,primaryImage_height,releaseYear_year,releaseYear_endYear,releaseDate_day,releaseDate_month,releaseDate_year,runtime_seconds,...,meterRanking_currentRank,meterRanking_rankChange_difference,productionBudget_budget_amount,lifetimeGross_total_amount,openingWeekendGross_gross_total_amount,worldwideGross_total_amount,plot_plotText,plot_language,prestigiousAwardSummary_nominations,prestigiousAwardSummary_wins
count,6128.000000,9025.000000,7336.000000,7336.000000,6966.000000,0.0,5432.00000,5667.000000,6734.000000,4662.000000,...,397.000000,397.000000,2.499000e+03,2.000000e+02,1.910000e+02,9.710000e+02,0.0,0.0,4.000000,4.000000
mean,6.117820,2985.822271,1931.651854,2568.559706,2021.008326,NaN,14.46539,6.242633,2021.154737,5771.386100,...,1815.790932,1152.657431,8.401640e+07,2.190556e+07,9.302873e+06,1.477100e+07,NaN,NaN,2.500000,0.750000
std,1.553708,23534.132854,1645.087556,2342.588647,2.644571,NaN,9.24193,3.717983,0.951580,1570.143249,...,1546.545936,5943.425028,1.467694e+09,6.090146e+07,2.590450e+07,7.784243e+07,NaN,NaN,1.914854,0.957427
min,1.000000,0.000000,174.000000,165.000000,1922.000000,NaN,1.00000,1.000000,1983.000000,420.000000,...,1.000000,0.000000,0.000000e+00,1.530000e+02,0.000000e+00,3.800000e+01,NaN,NaN,0.000000,0.000000
25%,5.100000,0.000000,896.000000,1080.000000,2021.000000,NaN,6.00000,3.000000,2021.000000,4980.000000,...,326.000000,48.000000,1.000000e+04,3.525375e+04,1.556850e+04,3.250600e+04,NaN,NaN,1.500000,0.000000
50%,6.200000,35.000000,1374.000000,1772.000000,2021.000000,NaN,14.00000,6.000000,2021.000000,5580.000000,...,1472.000000,224.000000,1.000000e+05,8.383715e+05,3.451570e+05,2.989750e+05,NaN,NaN,3.000000,0.500000
75%,7.200000,332.000000,2400.000000,3000.000000,2021.000000,NaN,22.00000,10.000000,2021.000000,6480.000000,...,3238.000000,745.000000,1.000000e+06,1.458614e+07,6.474923e+06,2.320902e+06,NaN,NaN,4.000000,1.250000
max,10.000000,886278.000000,16200.000000,24000.000000,2024.000000,NaN,31.00000,12.000000,2026.000000,28800.000000,...,4990.000000,106582.000000,5.000000e+10,6.274282e+08,2.601386e+08,1.386428e+09,NaN,NaN,4.000000,2.000000